name: better-near-auth

services:
  postgres:
    image: postgres
    container_name: better-near-auth-postgres
    environment:
      POSTGRES_DB: better-near-auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - better-near-auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  better-near-auth_postgres_data: